- id: 200
  key: satoshi
  currency: btc
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0005
  min_withdraw: 0.002
  type: WithdrawChannelSatoshi

- id: 201
  key: ethereum
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 0.01
  fee: 0.005
  min_withdraw: 0.01
  type: WithdrawChannelEthereum
