$ ->
  window.notifier = new Notifier()

  BigNumber.config(ERRORS: false)

  HeaderUI.attachTo('header')
  HeaderUI.attachTo('.livecoinprice')
  AccountSummaryUI.attachTo('#account_summary')

  FloatUI.attachTo('.float')
  KeyBindUI.attachTo(document)
  AutoWindowUI.attachTo(window)

  PlaceOrderUI.attachTo('#bid_entry')
  PlaceOrderUI.attachTo('#ask_entry')
  OrderBookUI.attachTo('#order_book')
  DepthUI.attachTo('#depths_wrapper')

  MyOrdersUI.attachTo('#my_orders')
  MarketTickerUI.attachTo('#ticker')
  MarketLastTickerUI.attachTo('#ticker_last')
  MarketSwitchUI.attachTo('#market_list_wrapper')
  MarketTradesUI.attachTo('#market_trades_wrapper')

  MarketData.attachTo(document)
  GlobalData.attachTo(document, {pusher: window.pusher})
  MemberData.attachTo(document, {pusher: window.pusher}) if gon.accounts

  CandlestickUI.attachTo('#candlestick')
  SwitchUI.attachTo('#range_switch, #indicator_switch, #main_indicator_switch, #type_switch')

  $('.panel-body-content').niceScroll
    autohidemode: true
    cursorborder: "none"

  $('.themeBox').click ->
    lighttheme_selected = $(this).hasClass('lightTheme')
    document.getElementById('lightTheme').setAttribute 'href', if lighttheme_selected then '/assets/market_lighttheme' else ''
    setTimeout ->
      if lighttheme_selected then tvWidget.changeTheme('light') else tvWidget.changeTheme('dark')
    , 100

  $('.chartBtn').click ->
    if $('.chartBox').hasClass('active') == false
      $('.chartBox').addClass 'active'
      $('body').css 'overflow-y', 'hidden'
    else
      $('.chartBox').removeClass 'active' 
      $('body').css 'overflow-y', 'auto'

  $('.marketDropdown').on 'click', (e) ->
    $('#marketDropdownMenu').toggleClass 'open'
    return
  $(document).on 'click', (e) ->
    if $(e.target).is('#marketDropdownMenu, .marketDropdown') == false
      $('#marketDropdownMenu').removeClass 'open'

  temp_orderbook = $('div#trade_orderbook').height()
  int_orderbook = temp_orderbook - 138
  # $('.coin_pair .data_tbody').css 'height', int_orderbook

  # ---
  # generated by js2coffee 2.2.0